### Réponse 01:

In [3]:
import pandas as pd #importer une bibliothèque d'analyse de données
df = pd.DataFrame(pd.read_csv("fr_population.csv")) #lire la base de donnée avec l'objet de pandas "data frame" est une présentation des données sous forme d'un tableau 
d=df[df['Zone']!="Chine"].copy() # pour enlever les informations redondantes
pop=sum(d.Valeur)*1000 #multiplier la somme des valeur par l'unité
print('le nombre total d’humains sur la planète est :', pop,'personnes' )# afficher la valeur de la population 
d.head(50)

le nombre total d’humains sur la planète est : 6997326000 personnes

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,511,Population totale,2501,Population,2013,2013,1000 personnes,30552,NaN,Donnée officielle
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,202,Afrique du Sud,511,Population totale,2501,Population,2013,2013,1000 personnes,52776,NaN,Donnée officielle
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,3,Albanie,511,Population totale,2501,Population,2013,2013,1000 personnes,3173,NaN,Donnée officielle
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,4,Algérie,511,Population totale,2501,Population,2013,2013,1000 personnes,39208,NaN,Donnée officielle
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,79,Allemagne,511,Population totale,2501,Population,2013,2013,1000 personnes,82727,NaN,Donnée officielle
5,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,7,Angola,511,Population totale,2501,Population,2013,2013,1000 personnes,21472,NaN,Donnée officielle
6,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,8,Antigua-et-Barbuda,511,Population totale,2501,Population,2013,2013,1000 personnes,90,NaN,Donnée officielle
7,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,194,Arabie saoudite,511,Population totale,2501,Population,2013,2013,1000 personnes,28829,NaN,Donnée officielle
8,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,9,Argentine,511,Population totale,2501,Population,2013,2013,1000 personnes,41446,NaN,Donnée officielle
9,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,1,Arménie,511,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle
10,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,10,Australie,511,Population totale,2501,Population,2013,2013,1000 personnes,23343,NaN,Donnée officielle
11,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,11,Autriche,511,Population totale,2501,Population,2013,2013,1000 personnes,8495,NaN,Donnée officielle
12,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,52,Azerbaïdjan,511,Population totale,2501,Population,2013,2013,1000 personnes,9413,NaN,Donnée officielle
13,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,12,Bahamas,511,Population totale,2501,Population,2013,2013,1000 personnes,377,NaN,Donnée officielle
14,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,16,Bangladesh,511,Population totale,2501,Population,2013,2013,1000 personnes,156595,NaN,Donnée officielle
15,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,14,Barbade,511,Population totale,2501,Population,2013,2013,1000 personnes,285,NaN,Donnée officielle
16,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,57,Bélarus,511,Population totale,2501,Population,2013,2013,1000 personnes,9357,NaN,Donnée officielle
17,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,255,Belgique,511,Population totale,2501,Population,2013,2013,1000 personnes,11104,NaN,Donnée officielle
18,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,23,Belize,511,Population totale,2501,Population,2013,2013,1000 personnes,332,NaN,Donnée officielle
19,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,53,Bénin,511,Population totale,2501,Population,2013,2013,1000 personnes,10323,NaN,Donnée officielle
20,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,17,Bermudes,511,Population totale,2501,Population,2013,2013,1000 personnes,65,NaN,Donnée officielle
21,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,19,Bolivie (État plurinational de),511,Population totale,2501,Population,2013,2013,1000 personnes,10671,NaN,Donnée officielle
22,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,80,Bosnie-Herzégovine,511,Population totale,2501,Population,2013,2013,1000 personnes,3829,NaN,Donnée officielle
23,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,20,Botswana,511,Population totale,2501,Population,2013,2013,1000 personnes,2021,NaN,Donnée officielle
24,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,21,Brésil,511,Population totale,2501,Population,2013,2013,1000 personnes,200362,NaN,Donnée officielle
25,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,26,Brunéi Darussalam,511,Population totale,2501,Population,2013,2013,1000 personnes,418,NaN,Donnée officielle
26,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,27,Bulgarie,511,Population totale,2501,Population,2013,2013,1000 personnes,7223,NaN,Donnée officielle
27,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,233,Burkina Faso,511,Population totale,2501,Population,2013,2013,1000 personnes,16935,NaN,Donnée officielle
28,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,35,Cabo Verde,511,Population totale,2501,Population,2013,2013,1000 personnes,499,NaN,Donnée officielle
29,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,115,Cambodge,511,Population totale,2501,Population,2013,2013,1000 personnes,15135,NaN,Donnée officielle
30,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,32,Cameroun,511,Population totale,2501,Population,2013,2013,1000 personnes,22254,NaN,Donnée officielle
31,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,33,Canada,511,Population totale,2501,Population,2013,2013,1000 personnes,35182,NaN,Donnée officielle
32,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,40,Chili,511,Population totale,2501,Population,2013,2013,1000 personnes,17620,NaN,Donnée officielle
34,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,96,Chine - RAS de Hong-Kong,511,Population totale,2501,Population,2013,2013,1000 personnes,7204,NaN,Donnée officielle
35,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,128,Chine - RAS de Macao,511,Population totale,2501,Population,2013,2013,1000 personnes,566,NaN,Donnée officielle
36,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,41,"Chine, continentale",511,Population totale,2501,Population,2013,2013,1000 personnes,1385567,NaN,Donnée officielle
37,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,214,"Chine, Taiwan Province de",511,Population totale,2501,Population,2013,2013,1000 personnes,23330,NaN,Donnée officielle
38,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,50,Chypre,511,Population totale,2501,Population,2013,2013,1000 personnes,1141,NaN,Donnée officielle
39,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,44,Colombie,511,Population totale,2501,Population,2013,2013,1000 personnes,48321,NaN,Donnée officielle
40,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,46,Congo,511,Population totale,2501,Population,2013,2013,1000 personnes,4448,NaN,Donnée officielle
41,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,48,Costa Rica,511,Population totale,2501,Population,2013,2013,1000 personnes,4872,NaN,Donnée officielle
42,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,107,Côte d'Ivoire,511,Population totale,2501,Population,2013,2013,1000 personnes,20316,NaN,Donnée officielle
43,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,98,Croatie,511,Population totale,2501,Population,2013,2013,1000 personnes,4290,NaN,Donnée officielle
44,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,49,Cuba,511,Population totale,2501,Population,2013,2013,1000 personnes,11266,NaN,Donnée officielle
45,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,54,Danemark,511,Population totale,2501,Population,2013,2013,1000 personnes,5619,NaN,Donnée officielle
46,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,72,Djibouti,511,Population totale,2501,Population,2013,2013,1000 personnes,873,NaN,Donnée officielle
47,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,55,Dominique,511,Population totale,2501,Population,2013,2013,1000 personnes,72,NaN,Donnée officielle
48,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,59,Égypte,511,Population totale,2501,Population,2013,2013,1000 personnes,82056,NaN,Donnée officielle
49,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,60,El Salvador,511,Population totale,2501,Population,2013,2013,1000 personnes,6340,NaN,Donnée officielle
50,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,225,Émirats arabes unis,511,Population totale,2501,Population,2013,2013,1000 personnes,9346,NaN,Donnée officielle

### Réponse 02:
Formule 01:(Quantité exprimé en milliers de tonnes)

Disponibilité intérieure= production + importation + variation stock - exportation.

Formule 02:(Quantité exprimé en milliers de tonnes)

Disponibilité intérieure= aliments pour animaux + semences + perte + traitement + autres utilisation (non alimentaire) + nourriture.

#### Illustration avec l'exemple du blé pour la france

In [2]:
df_veg=pd.DataFrame(pd.read_csv("fr_vegetaux.csv"))#lire la base de donnée 
fr_bl=df_veg[(df_veg['Zone']=="France")&(df_veg['Produit']=="Blé")]#étudier la base de données avec le blé de la france (que m'intéresse)
di=fr_bl[(fr_bl['Élément']=="Disponibilité intérieure")].Valeur.sum()#sélectionner la valeur de la disponibilité intèrieur
print('Disponiblité intèrieur est:' ,di)# afficher la valeur de la disponibilité intèrieur

Disponiblité intèrieur est: 20298.0

In [3]:
pr=fr_bl[fr_bl['Élément']=="Production"]['Valeur'].sum()
im=fr_bl[fr_bl['Élément']=="Importations - Quantité"].Valeur.sum()#j'ai mis la fonction sum au lieu de values juste pour l'affichage
var=fr_bl[fr_bl['Élément']=="Variation de stock"].Valeur.sum()
ex=fr_bl[(fr_bl['Élément']=="Exportations - Quantité")].Valeur.sum()
print('Disponiblité intèrieur calculée à partir la première formule est:' ,im+var+pr-ex )

Disponiblité intèrieur calculée à partir la première formule est: 20298.0

In [4]:
pe=fr_bl[(fr_bl['Élément']=="Pertes")].Valeur.sum()
tr=fr_bl[(fr_bl['Élément']=="Traitement")].Valeur.sum()
nr=fr_bl[(fr_bl['Élément']=="Nourriture")].Valeur.sum()
al_ani=fr_bl[(fr_bl['Élément']=="Aliments pour animaux")].Valeur.sum()
aut_ut=fr_bl[(fr_bl['Élément']=="Autres utilisations (non alimentaire)")].Valeur.sum()
sm=fr_bl[(fr_bl['Élément']=="Semences")].Valeur.sum()
print('Disponiblité intèrieur calculée à partir la deuxième formule est:',al_ani+sm+pe+tr+aut_ut+nr)

Disponiblité intèrieur calculée à partir la deuxième formule est: 20298.0

### Réponse 03:

In [5]:
df_ani=pd.DataFrame(pd.read_csv("fr_animaux.csv")) #lire la base de donnée 
df_ani_veg=pd.concat([df_ani, df_veg], ignore_index=True) # faire concatiner les deux tableaux fr_ani fr_veg pour avoir tous les produits dans un seul tab
df_ani_veg.rename(columns={'Valeur':'Valeur_produit'}, inplace=True)# renommer Valeur pour non pas confondus entre les deux colonnes qd on fusionne les 2 tab 
d.rename(columns={'Valeur':'Valeur_population'}, inplace=True) #             /////////////         /////////////
#étudier d au lieu df car d il contient pas la chine 
ddf=d[['Zone', 'Valeur_population']]#créer d'autre tab à partir d pour ne pas confondus entre les titres des colonnes élément les produits ... etc et prendre juste ce qu'on a besoin 
df_pop_ani_veg=pd.merge(ddf,df_ani_veg,on='Zone')# fusionner les 2 tab pour faire les calculs
df_pop_ani_veg_disp=df_pop_ani_veg[df_pop_ani_veg['Élément']=="Disponibilité alimentaire (Kcal/personne/jour)"].copy()#sélectionner les valeurs de la disp alimentaire pour chaque pays et chaque produit 
df_pop_ani_veg['Disponibilité alimentaire en kcal']=df_pop_ani_veg_disp['Valeur_population']*df_pop_ani_veg_disp['Valeur_produit']*365*1000 #ajouter une colonne de la disp alimentaire en kcal  
df_disp=df_pop_ani_veg.loc[df_pop_ani_veg['Élément']=="Disponibilité alimentaire (Kcal/personne/jour)",['Zone','Produit','Valeur_produit','Disponibilité alimentaire en kcal']]#séléctionner les colonnes qu'on veut afficher 
df_disp.rename(columns={'Valeur_produit':'Disponibilité alimentaire (Kcal/personne/jour)'}, inplace=True)
df_disp

,Zone,Produit,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en kcal
5,Afghanistan,Viande de Bovins,27.0,3.010900e+11
12,Afghanistan,Viande d'Ovins/Caprins,31.0,3.456959e+11
20,Afghanistan,Viande de Volailles,9.0,1.003633e+11
28,Afghanistan,"Viande, Autre",1.0,1.115148e+10
35,Afghanistan,Abats Comestible,5.0,5.575740e+10
...,...,...,...,...
140884,Zimbabwe,Bière,24.0,1.239540e+11
140892,Zimbabwe,Boissons Fermentés,10.0,5.164750e+10
140901,Zimbabwe,Boissons Alcooliques,42.0,2.169195e+11
140913,Zimbabwe,Aliments pour enfants,0.0,0.000000e+00
140916,Zimbabwe,Miscellanees,2.0,1.032950e+10

In [6]:
df_pop_ani_veg_pro=df_pop_ani_veg[(df_pop_ani_veg['Élément']=="Disponibilité de protéines en quantité (g/personne/jour)")]#sélectionner les valeurs de la disp alimentaire de protéines pour chaque pays et chaque produit 
df_pop_ani_veg['Disponibilité alimentaire en kg de protéines']=df_pop_ani_veg_pro['Valeur_population']*df_pop_ani_veg_pro['Valeur_produit']*365*1000*0.001#ajouter une colonne de la disp alimentaire de protéines en kg  
df_pro=df_pop_ani_veg.loc[df_pop_ani_veg['Élément']=="Disponibilité de protéines en quantité (g/personne/jour)",['Zone','Produit','Valeur_produit','Disponibilité alimentaire en kg de protéines']] 
df_pro.rename(columns={'Valeur_produit':'Disponibilité de protéines en quantité (g/personne/jour)'}, inplace=True)
df_pro

,Zone,Produit,Disponibilité de protéines en quantité (g/personne/jour),Disponibilité alimentaire en kg de protéines
6,Afghanistan,Viande de Bovins,1.89,21076297.2
13,Afghanistan,Viande d'Ovins/Caprins,1.91,21299326.8
21,Afghanistan,Viande de Volailles,0.87,9701787.6
29,Afghanistan,"Viande, Autre",0.17,1895751.6
36,Afghanistan,Abats Comestible,0.77,8586639.6
...,...,...,...,...
140867,Zimbabwe,"Épices, Autres",0.02,103295.0
140885,Zimbabwe,Bière,0.28,1446130.0
140893,Zimbabwe,Boissons Fermentés,0.13,671417.5
140914,Zimbabwe,Aliments pour enfants,0.00,0.0
140917,Zimbabwe,Miscellanees,0.07,361532.5

### Réponse 04:

In [7]:
 df_pop_ani_veg_nou=df_pop_ani_veg.loc[(df_pop_ani_veg['Élément']=="Nourriture")&(df_pop_ani_veg['Valeur_produit']!=0),['Zone','Produit','Valeur_produit']]#sélectionner les valeurs de la nourriture non nuls pour chaque pays et chaque produit (pour éviter la division sur 0)
df_ratio_kcal=df_disp.merge(df_pop_ani_veg_nou,on=['Zone','Produit'])# fusionner les 2 tab pour faire les calculs
df_ratio_kcal['Ratio (kcal/kg)']=df_ratio_kcal['Disponibilité alimentaire en kcal']/(df_ratio_kcal['Valeur_produit']*1000000)# multiplier la valeur de produit par 1000000 pour faire une transformation d'unité(milliers de tonne-> kg)
df_pop_ani_veg['Ratio (kcal/kg)']=df_ratio_kcal['Ratio (kcal/kg)']# ajouter une colonne Ratio (kcal/kg)
df_ratio_kcal

,Zone,Produit,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en kcal,Valeur_produit,Ratio (kcal/kg)
0,Afghanistan,Viande de Bovins,27.0,3.010900e+11,140.0,2150.642571
1,Afghanistan,Viande d'Ovins/Caprins,31.0,3.456959e+11,150.0,2304.639200
2,Afghanistan,Viande de Volailles,9.0,1.003633e+11,75.0,1338.177600
3,Afghanistan,"Viande, Autre",1.0,1.115148e+10,12.0,929.290000
4,Afghanistan,Abats Comestible,5.0,5.575740e+10,53.0,1052.026415
...,...,...,...,...,...,...
9992,Zimbabwe,"Épices, Autres",1.0,5.164750e+09,1.0,5164.750000
9993,Zimbabwe,Vin,1.0,5.164750e+09,4.0,1291.187500
9994,Zimbabwe,Bière,24.0,1.239540e+11,292.0,424.500000
9995,Zimbabwe,Boissons Fermentés,10.0,5.164750e+10,148.0,348.969595
9996,Zimbabwe,Boissons Alcooliques,42.0,2.169195e+11,73.0,2971.500000

In [8]:
print(df_ratio_kcal.loc[df_ratio_kcal['Produit']=="Oeufs",['Ratio (kcal/kg)']].mean().sum(),'kcal/kg')# exemple de vérification sur le site la valeur calorique 147 kcal pour 100g donc 1470 kcal/kg

1345.3003859252406 kcal/kg

In [9]:
df_ratio_kg=df_pro.merge(df_pop_ani_veg_nou,on=['Zone','Produit'])# fusionner les 2 tab pour faire les calculs
df_ratio_kg['Ratio (kg/kg)']=df_ratio_kg['Disponibilité alimentaire en kg de protéines']*100/(df_ratio_kg['Valeur_produit']*1000000)#*100 calculer le pourcentage de protéines
df_ratio_kg[['Zone','Produit','Ratio (kg/kg)']]
df_pop_ani_veg['Ratio (kg/kg)']=df_ratio_kg['Ratio (kg/kg)']# ajouter une colonne Ratio (kg/kg)
df_ratio_kg

,Zone,Produit,Disponibilité de protéines en quantité (g/personne/jour),Disponibilité alimentaire en kg de protéines,Valeur_produit,Ratio (kg/kg)
0,Afghanistan,Viande de Bovins,1.89,21076297.2,140.0,15.054498
1,Afghanistan,Viande d'Ovins/Caprins,1.91,21299326.8,150.0,14.199551
2,Afghanistan,Viande de Volailles,0.87,9701787.6,75.0,12.935717
3,Afghanistan,"Viande, Autre",0.17,1895751.6,12.0,15.797930
4,Afghanistan,Abats Comestible,0.77,8586639.6,53.0,16.201207
...,...,...,...,...,...,...
8717,Zimbabwe,Poivre,0.03,154942.5,2.0,7.747125
8718,Zimbabwe,Piments,0.22,1136245.0,10.0,11.362450
8719,Zimbabwe,"Épices, Autres",0.02,103295.0,1.0,10.329500
8720,Zimbabwe,Bière,0.28,1446130.0,292.0,0.495250
8721,Zimbabwe,Boissons Fermentés,0.13,671417.5,148.0,0.453660

In [10]:
 # exemple de vérification selon le wikipedia la valeur est 10.7g pour 100g donc 0.107 kg/kg (10.7%)
print(df_ratio_kg.loc[(df_ratio_kg['Produit']=="Avoine"),['Ratio (kg/kg)']].mean().sum(),'%')# calcluer la moyenne

8.177493361542373 %

### Réponse 05:

In [11]:
pr_df_ratio_kcal=df_ratio_kcal.groupby("Produit")['Ratio (kcal/kg)'].mean()#Calculer la moyenne de la ratio(kcal/kg) de chaque produit
pr_df_ratio_kg=df_ratio_kg.groupby("Produit")['Ratio (kg/kg)'].mean()#Calculer la moyenne de la ratio(kg/kg) de chaque produit
ratio=pd.DataFrame({"ratio_kal/kg":pr_df_ratio_kcal, "ratio_kg/kg":pr_df_ratio_kg})#Créer une nouvelle table
ratio.sort_values("ratio_kal/kg", ascending=False).head(5)# classer les valeurs en ordre décroissant et afficher les cinq premiers

                        ratio_kal/kg  ratio_kg/kg
Huiles de Poissons       9003.715504     0.000000
Huile de Palmistes       8789.540277     0.304681
Huile de Palme           8719.419872     0.386137
Huile de Germe de Maïs   8649.968502     0.187364
Huile de Son de Riz      8641.430661     0.692650

In [12]:
ratio.sort_values("ratio_kg/kg", ascending=False)[:5]# classer les valeurs du plus grand au plus petit et afficher les cind premiers

                        ratio_kal/kg  ratio_kg/kg
Soja                     2376.843544    28.533053
Arachides Decortiquees   5620.249374    25.146613
Pois                     3443.737407    22.324375
Légumineuses Autres      3339.891537    21.806434
Haricots                 3341.783779    21.545181

### Réponse 06:

In [13]:
df_veg_pop=ddf.merge(df_veg, on='Zone')# fusionner les 2 tab df_veg et ddf (pour ne pas prendre la chine en considération)
df_veg_dis=df_veg_pop.loc[df_veg_pop['Élément']=="Disponibilité intérieure",['Produit','Valeur']]#sélectionner les valeurs de la disp intérieur pour chaque pays et chaque produit végétaux 
df_veg_dis['disponibilité intérieure(kg)']=df_veg_dis['Valeur']*1000000 # calculer la disponibilité intérieur en kg
disp_kg=df_veg_dis.groupby('Produit')['disponibilité intérieure(kg)'].sum()# calculer la somme de la disponibilité int de chaque produit 
veget=ratio.merge(disp_kg,left_index=True, right_index=True)#utiliser l'index comme clé de jointure pour la fusion des DataFrames
veget['disponibilité intérieure(kcal)']=veget['ratio_kal/kg']*veget['disponibilité intérieure(kg)']# calculer la disponibilité intèrieure en kcal par produit 
disp_int_mondiale=veget['disponibilité intérieure(kcal)'].sum()#calculer la somme des kilo calories  
print("la disponibilité intérieure mondiale pour les produits végétaux exprimée en kcal est:",disp_int_mondiale)

la disponibilité intérieure mondiale pour les produits végétaux exprimée en kcal est: 1.3095798424730492e+16

### Réponse 07:

In [14]:
humaine_nourr=disp_int_mondiale/(365*2500)# une personne a besoin 2500 kcal par jour
print("Nombre de personnes qui peuvent être nourries si toute la disponibilité intérieure mondiale des produits végétaux  était utilisée pour la nourriture en terme de calories est: ",humaine_nourr)
print("en pourcentage",humaine_nourr/pop*100,'%')# diviser par le nombre total de la population

Nombre de personnes qui peuvent être nourries si toute la disponibilité intérieure mondiale des produits végétaux  était utilisée pour de la nourriture en terme de calories est:  14351559917.512869
en pourcentage 205.1006329776956 %

In [15]:
veget['disp_int_protéines(kg)']=veget['ratio_kg/kg']*veget['disponibilité intérieure(kg)']*0.01 # calculer la disp int en terme de protéines par produit (multipluier par 0.01 psq on a les valeurs en pourcentage)
disp_int_kg_mondiale=veget['disp_int_protéines(kg)'].sum()# calculer la somme total
humaine_nourr_pro=disp_int_kg_mondiale/(365*0.060)# une personne a besoin 60 g par jour
print("Nombre de personnes qui peuvent être nourries si toute la disponibilité intérieure mondiale des produits végétaux  était utilisée pour la nourriture en terme de protéines est: ",humaine_nourr_pro)
print("en pourcentage",humaine_nourr_pro/pop*100,'%')# diviser par le nombre total de la population

Nombre de personnes qui peuvent être nourries si toute la disponibilité intérieure mondiale des produits végétaux  était utilisée pour de la nourriture en terme de protéines est:  14872068264.109858
en pourcentage 212.53930807439664 %

### Réponse 08:

In [16]:
df_veg_pert=df_veg_pop.loc[(df_veg_pop['Élément']=="Pertes")|(df_veg_pop['Élément']=="Aliments pour animaux")|(df_veg_pop['Élément']=="Disponibilité intérieure"),['Produit','Valeur']]#sélectionner les valeurs (pertes, aliments pour animaux, disp int) pour chaque pays et chaque produit végétaux
df_veg_pert['disp_int/pertes/ali_animaux(kg)']=df_veg_pert['Valeur']*1000000 # la quantité en kg
per_ali=df_veg_pert.groupby('Produit')['disp_int/pertes/ali_animaux(kg)'].sum()#calculer la somme pour chaque produit 
veget_per=ratio.merge(per_ali,left_index=True, right_index=True)#utiliser l'index comme clé de jointure pour la fusion des DataFrames
veget_per['disp_int/pertes/ali_animaux(kcal)']=veget_per['ratio_kal/kg']*veget_per['disp_int/pertes/ali_animaux(kg)']#calculer la quantité en terme d'energie 
per_ali_kcal_mondiale=veget_per['disp_int/pertes/ali_animaux(kcal)'].sum()#calculer la somme des kilo calories  
print("énergie totale en kcal est:",per_ali_kcal_mondiale)
veget_per['disp_int/pertes/ali_animaux(kg)']=veget_per['ratio_kg/kg']*veget_per['disp_int/pertes/ali_animaux(kg)']*0.01 #calculer la quantité en terme de protéines par produit
per_ali_kg_mondiale=veget_per['disp_int/pertes/ali_animaux(kg)'].sum()
print("protéines totales en kg est:",per_ali_kg_mondiale)

énergie totale en kcal est: 1.6444556350335282e+16
protéines totales en kg est: 414078002970.87213

In [17]:
humaine_nou=per_ali_kcal_mondiale/(365*2500)# une personne a besoin 2500 kcal par jour
print("Nombre de personnes qui peuvent être nourries en terme de calories est:",humaine_nou)
print("en pourcentage",humaine_nou/pop*100,'%')# diviser par le nombre total de la population

Nombre de personnes qui peuvent être nourries en terme de calories est: 18021431616.80579
en pourcentage 257.5474062063964 %

In [18]:
humaine_nou_pro=per_ali_kg_mondiale/(365*0.060)# une personne a besoin 60 g par jour
print("Nombre de personnes qui peuvent être nourries en terme de protéines est:",humaine_nou_pro)
print("en pourcentage",humaine_nou_pro/pop*100,'%')# diviser par le nombre total de la population

Nombre de personnes qui peuvent être nourries en terme de protéines est: 18907671368.532974
en pourcentage 270.2128122733309 %

### Réponse 09:

In [19]:
df_pop_ani_veg_int=df_pop_ani_veg.loc[df_pop_ani_veg['Élément']=="Disponibilité intérieure",['Produit','Valeur_produit']]#sélectionner les valeurs de la disp intérieur pour chaque pays et chaque produit
df_pop_ani_veg_int['disponibilité intérieure(kg)']=df_pop_ani_veg_int['Valeur_produit']*1000000 # la disponibilité intérieur en kg
disp_int_kg=df_pop_ani_veg_int.groupby('Produit')['disponibilité intérieure(kg)'].sum()# calculer la somme de la disponibilité int de chaque produit 
veg_ani_int=ratio.merge(disp_int_kg,left_index=True, right_index=True)#utiliser l'index comme clé de jointure pour la fusion des DataFrames
veg_ani_int['disponibilité intérieure(kcal)']=veg_ani_int['ratio_kal/kg']*veg_ani_int['disponibilité intérieure(kg)']# calculer la disponibilité intèrieure en kcal par produit
disp_int_mondiale_kcal=veg_ani_int['disponibilité intérieure(kcal)'].sum()#calculer la somme des kilo calories
print("la disponibilité intérieure mondiale exprimée en kcal est:",disp_int_mondiale_kcal)
veg_ani_int['protéines totales']=veg_ani_int['ratio_kg/kg']*veg_ani_int['disponibilité intérieure(kg)']*0.01 # calculer la disp int en terme de protéines par produit
dis_int_kg_mondiale=veg_ani_int['protéines totales'].sum()
print("protéines totales en kg est:",dis_int_kg_mondiale)

la disponibilité intérieure mondiale exprimée en kcal est: 1.4575229616181458e+16
protéines totales en kg est: 415878217787.6411

In [32]:
humaine_nourr_disp=disp_int_mondiale_kcal/(365*2500)# une personne a besoin 2500 kcal par jour
print("Nombre de personnes qui peuvent être nourries avec la disponibilité intérieure mondiale en terme de calories est: ",humaine_nourr_disp)
print("en pourcentage",humaine_nourr_disp/pop*100,'%')# diviser par le nombre total de la population

Nombre de personnes qui peuvent être nourries avec la disponibilité intérieure mondiale en terme de calories est:  15972854373.897488
en pourcentage 228.27083337116903 %

In [33]:
humaine_nou_disp_pro=dis_int_kg_mondiale/(365*0.060)# une personne a besoin 60 g par jour
print("Nombre de personnes qui peuvent être nourries avec la disponibilité intérieure mondiale en terme de protéines est: ",humaine_nou_disp_pro)
print("en pourcentage",humaine_nou_disp_pro/pop*100,'%')# diviser par le nombre total de la population

Nombre de personnes qui peuvent être nourries avec la disponibilité intérieure mondiale en terme de protéines est:  18989872958.33978
en pourcentage 271.3875694563863 %

### Réponse 10:

In [22]:
df_sous_ali = pd.DataFrame(pd.read_csv("fr_sousalimentation.csv"))#lire la base de donnée  
df_sous_ali_2013=df_sous_ali[(df_sous_ali['Année']=="2012-2014")&(df_sous_ali['Zone']!="Chine")].copy() # selectionner les données en 2013 
df_sous_ali_2013['Valeur']=pd.to_numeric(df_sous_ali_2013['Valeur'],errors='coerce')#convertir l’argument en un type numérique( remplacer <0.1 par nan)
nb=df_sous_ali_2013['Valeur'].sum()*1000000 # calculer la population mondiale totale considérée comme sous-alimentée
print(nb/pop*100,'% de personne sous alimenté dans le monde')

10.628345742359295 % de personne sous alimenté dans le monde

### Réponse 11:

In [23]:
df_céréales = pd.DataFrame(pd.read_csv("fr_céréales.csv"))#lire la base de donnée 
df_pop_ani_veg['is_céréal']=df_pop_ani_veg['Produit'].isin(df_céréales['Produit'])#ajouter une colonne de type booléen il ne retourne True que lorsque le produit est identique
df_fr_céréal=df_pop_ani_veg[((df_pop_ani_veg['Élément']=="Nourriture")|(df_pop_ani_veg['Élément']=="Aliments pour animaux"))&df_pop_ani_veg['is_céréal']==True].copy()
df_fr_céréal_ali=df_fr_céréal[(df_fr_céréal['Élément']=="Aliments pour animaux")].copy() #sélectionner les valeurs d'alimants pour animaux
print(df_fr_céréal_ali['Valeur_produit'].sum()/df_fr_céréal['Valeur_produit'].sum()*100,"% distinée à l'alimentation animale ")

45.91402568664604 % distinée à l'alimentation animale

### Réponse 12:

In [24]:
pay_sous_ali=df_sous_ali_2013.loc[(df_sous_ali_2013['Valeur']>0),['Zone']]#sélectionner les pays dans lesquels la FAO recense des personnes en sous-nutrition en 2013
df_pay_souali=df_pop_ani_veg.merge(pay_sous_ali,on=['Zone'])# fusionner les 02 tab pour obtenir plus d'informations sur les pays souffrant de sous-nutrition
df_pay_souali=df_pay_souali.loc[df_pay_souali['Élément']=="Exportations - Quantité",['Zone','Produit','Valeur_produit']]#sélectionner les valeurs de l'exportations
df_pay_souali.rename(columns={'Valeur_produit':'Exportations'}, inplace=True)# renommer Valeur_produit par exportation
df_pro_pay=df_pay_souali.groupby('Produit')['Exportations'].sum().reset_index()# calculer la somme des valeurs de chaque produit 
df_pro_pay=df_pro_pay.sort_values( 'Exportations',ascending=False)[:15]# classer les valeurs du plus grand au plus petit et afficher les quinze premiers pays
df_pro_pay

                Produit  Exportations
39       Huile de Palme       46285.0
52                 Maïs       37888.0
51               Manioc       35843.0
78     Riz (Eq Blanchi)       32787.0
82        Sucre Eq Brut       25237.0
12                  Blé       24841.0
49      Légumes, Autres       19948.0
8               Bananes       17805.0
25       Fruits, Autres       14590.0
48   Lait - Excl Beurre       14486.0
80                 Soja       14389.0
72  Poissons Pelagiques       13680.0
88              Tomates        8901.0
74               Pommes        7786.0
60  Oranges, Mandarines        6838.0

In [25]:
df_merg_bilan_pro=df_pop_ani_veg.merge(df_pro_pay,on=['Produit'])#fusionner les deux tab pour obtenir tous les info concernant les quinze produits les plus exportés par les pays dans lesquels la FAO recense des personnes en sous-nutrition en 2013 
piv1=df_merg_bilan_pro.pivot_table(index=['Zone','Produit'],columns='Élément',values='Valeur_produit')#utiliser des éléments présentes dans colonne "Élément" comme noms de colonnes 
piv1.reset_index(inplace=True)# réintégrer les lignes de l'index comme colonnes simples
df_p=piv1.sort_values('Importations - Quantité', ascending=False)[:200]# classer les valeurs de l'importation en ordre croissant et afficher les 200 premiers
df_p[['Zone','Produit','Importations - Quantité']]

Élément                 Zone             Produit  Importations - Quantité
549      Chine, continentale                Soja                  63381.0
543      Chine, continentale              Manioc                  29046.0
1156                   Japon                Maïs                  14403.0
2494                  Égypte                 Blé                  10331.0
1928     République de Corée                Maïs                   8755.0
...                      ...                 ...                      ...
1382                Malaisie    Riz (Eq Blanchi)                   1079.0
1124                  Italie     Légumes, Autres                   1061.0
2438                Viet Nam  Lait - Excl Beurre                   1041.0
1803                 Pologne                 Blé                   1037.0
469                   Canada                Maïs                   1035.0

[200 rows x 3 columns]

In [26]:
df_pr=piv1.groupby('Produit')[['Importations - Quantité','Autres utilisations (non alimentaire)','Disponibilité intérieure','Aliments pour animaux','Nourriture']].sum().reset_index()# calculer la somme (importation, autre utilisations, disp int, alim pour anim, nourriture) de chaque produit
df_pr['Ratio_AutreUti_DispInt']=df_pr['Autres utilisations (non alimentaire)']/df_pr['Disponibilité intérieure']#calculer le ratio entre la quantité destinés aux "Autres utilisations" et la disponibilité intérieure.
df_pr['Ratio_animaux_nourriture']=df_pr['Aliments pour animaux']/(df_pr['Nourriture']+df_pr['Aliments pour animaux'])#calculer le ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine)
df_pr

Élément,Produit,Importations - Quantité,Autres utilisations (non alimentaire),Disponibilité intérieure,Aliments pour animaux,Nourriture,Ratio_AutreUti_DispInt,Ratio_animaux_nourriture
0,Bananes,19424.0,142.0,103992.0,871.0,85954.0,0.001365,0.010032
1,Blé,185377.0,22424.0,679498.0,129668.0,457824.0,0.033001,0.220714
2,"Fruits, Autres",31963.0,128.0,205956.0,61.0,185475.0,0.000621,0.000329
3,Huile de Palme,48858.0,35191.0,50409.0,0.0,15214.0,0.698109,0.000000
4,Lait - Excl Beurre,116806.0,18768.0,748864.0,81973.0,629738.0,0.025062,0.115177
5,"Légumes, Autres",43333.0,490.0,881716.0,49366.0,762130.0,0.000556,0.060833
6,Manioc,38370.0,35987.0,256664.0,87056.0,100637.0,0.140211,0.463821
7,Maïs,122691.0,189386.0,955799.0,546116.0,125184.0,0.198144,0.813520
8,"Oranges, Mandarines",35011.0,115.0,93728.0,11.0,86690.0,0.001227,0.000127
9,Poissons Pelagiques,28598.0,376.0,41024.0,18817.0,21687.0,0.009165,0.464571
10,Pommes,20025.0,42.0,83685.0,663.0,70671.0,0.000502,0.009294
11,Riz (Eq Blanchi),37618.0,18464.0,475656.0,33594.0,377286.0,0.038818,0.081761
12,Soja,102082.0,638.0,267445.0,17476.0,10648.0,0.002386,0.621391
13,Sucre Eq Brut,61615.0,13130.0,168864.0,90.0,143648.0,0.077755,0.000626
14,Tomates,18570.0,77.0,159452.0,1870.0,144080.0,0.000483,0.012813

In [27]:
df_pr.sort_values('Ratio_AutreUti_DispInt', ascending=False)[:3]#calculer les trois produits ayant la plus grande valeur pour le ratio entre la quantité destinée aux "autres utilisations" et la disponibilité intérieur

Élément,Produit,Importations - Quantité,Autres utilisations (non alimentaire),Disponibilité intérieure,Aliments pour animaux,Nourriture,Ratio_AutreUti_DispInt,Ratio_animaux_nourriture
3,Huile de Palme,48858.0,35191.0,50409.0,0.0,15214.0,0.698109,0.000000
7,Maïs,122691.0,189386.0,955799.0,546116.0,125184.0,0.198144,0.813520
6,Manioc,38370.0,35987.0,256664.0,87056.0,100637.0,0.140211,0.463821

In [28]:
df_pr.sort_values('Ratio_animaux_nourriture', ascending=False)[:3]#calculer les trois produits ayant la plus grande valeur pour le ratio entre la quantité destinée  à la nourriture animale et la quantité destinée à la nourriture (animale + humaine)

Élément,Produit,Importations - Quantité,Autres utilisations (non alimentaire),Disponibilité intérieure,Aliments pour animaux,Nourriture,Ratio_AutreUti_DispInt,Ratio_animaux_nourriture
7,Maïs,122691.0,189386.0,955799.0,546116.0,125184.0,0.198144,0.813520
12,Soja,102082.0,638.0,267445.0,17476.0,10648.0,0.002386,0.621391
9,Poissons Pelagiques,28598.0,376.0,41024.0,18817.0,21687.0,0.009165,0.464571

### Réponse 13:

In [29]:
df_céréales_USA=df_pop_ani_veg.loc[(df_pop_ani_veg['Zone']=="États-Unis d'Amérique")&(df_pop_ani_veg['is_céréal']==True),['Élément','Produit','Valeur_produit']]#sélectionner les valeur des céréales des états-unis d'amérique
df_céréales_USA_ali=df_céréales_USA.loc[(df_céréales_USA['Élément']=="Aliments pour animaux"),['Produit','Valeur_produit']]#sélectionner les valeurs des alimaents pour animaux
df_céréales_USA_ali_su=df_céréales_USA_ali['Valeur_produit'].sum()*10/100# calculer la quantité qui représente 10% de la production cerealieres USA destinés a l'alimentation des animaux
print('Si les USA diminuaient leur production de produits animaux de 10% la quantité de céréales que pourraient être libérées est', df_céréales_USA['Valeur_produit'].sum()-df_céréales_USA_ali_su,'milliers de tonnes')

Si les USA diminuaient leur production de produits animaux de 10% la quantité de céréales que pourraient être libérées est 1148556.3599999999 milliers de tonnes

### Réponse 14:

In [30]:
df_thailande=df_pop_ani_veg.loc[(df_pop_ani_veg['Zone']=="Thaïlande")&(df_pop_ani_veg['Produit']=="Manioc" ),['Élément','Valeur_produit','Valeur_population']]#sélectinner les valeurs de manioc de la thaïlande
df_thailande_exp=df_thailande[df_thailande['Élément']=='Exportations - Quantité'].Valeur_produit.sum()#calculer la somme des valeurs des exportations 
print(df_thailande_exp*100/df_thailande['Valeur_produit'].sum(),'% de manioc est exportée en Thaïlande')

36.39844503255924 % de manioc est exportée en Thaïlande

In [31]:
df_thailande_pop=df_thailande[df_thailande['Élément']=='Exportations - Quantité'].Valeur_population.sum()*1000 #définir la population totale de la thailande en 2013
df_thailande_sou_al=df_sous_ali_2013[df_sous_ali_2013['Zone']=="Thaïlande"].Valeur.sum()*1000000 #déterminer le nombre de la population thailandaise souffrant de malnutrition en 2013
print(df_thailande_sou_al*100/df_thailande_pop,'% de personne en sous-nutrition en Thaïlande')

8.356836937219262 % de personne en sous-nutrition en Thaïlande